USE SQLPractice
GO

DROP TABLE IF EXISTS dbo.Clientes
GO

CREATE TABLE dbo.Clientes
(
	IDCliente INTEGER IDENTITY (1,1) PRIMARY KEY,
	Nombre	NVARCHAR(255) NOT NULL,
	ApellidoPaterno NVARCHAR(255) NOT NULL,
	ApellidoMaterno NVARCHAR(255) NOT NULL,
	FechaNacimiento DATE NOT NULL,
	FechaRegistro DATE NOT NULL
)